---
name: Delete 2FA for Synapse User

on:
  workflow_call:
    inputs:
      USER_ID:
        required: true
        type: string
        description: ID of the user to delete 2FA for. This will allow a user who has lost their 2FA secret *and* forgotten their password to reset their password via email. This should only be done for users whose identity and account ownership are well-known to Sage Bionetworks.

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        run: |
          PIPELINE_PARAMETERS=\
          "CommandToExecute=\"scripts/delete_2fa_for_synapse_user.sh ${{ inputs.USER_ID }} ${{ vars.SYNAPSE_HOST }}\""

          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
