---
name: Deploy Synapse Global Resources (CodePipeline)

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
        description: dev or prod
      OPS_VPC_EXPORT_PREFIX:
        required: true
        type: string
        description: The prefix used when exporting VPC resources from ops VPC stack
      STACK_BUILDER_OWNER:
        required: false
        type: string
        default: Sage-Bionetworks
        description: Owner of Synapse-Stack-Builder repository, defaults to Sage-Bionetworks
      STACK_BUILDER_BRANCH:
        required: false
        type: string
        default: develop
        description: Branch of Synapse-Stack-Builder repository, defaults to develop

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Pipeline Parameters
        id: pipeline-params
        run: |
          PIPELINE_PARAMETERS="CommandToExecute=\"scripts/build_synapse_global_resources.sh ${{ inputs.STACK }} ${{ inputs.OPS_VPC_EXPORT_PREFIX }} \""
          echo "PIPELINE_PARAMETERS=$PIPELINE_PARAMETERS" >> $GITHUB_OUTPUT
    outputs:
      PIPELINE_PARAMETERS: ${{ steps.pipeline-params.outputs.PIPELINE_PARAMETERS }}

  invoke_pipeline:
    needs: set-up
    uses: "./.github/workflows/invoke_code_pipeline.yml"
    with:
      PIPELINE_PARAMETERS: ${{ needs.set-up.outputs.PIPELINE_PARAMETERS }}
      SECOND_REPO_NAME: Synapse-Stack-Builder
      SECOND_REPO_OWNER: ${{ inputs.STACK_BUILDER_OWNER }}
      SECOND_REPO_BRANCH: ${{ inputs.STACK_BUILDER_BRANCH }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
...
